services:
  element:
    image: vectorim/element-web@sha256:74b2e97b799c78fcc622141f13981da4f42188d0f85dc16e436cf29c751abf4a
    restart: unless-stopped
    configs:
      - source: element_config
        target: /app/config.json
    ports:
      - ${ELEMENT_PORTS}

configs:
  element_config:
    content: |
      {
        "default_server_config": {
          "m.homeserver": {
            "base_url": "${BASE_URL}",
            "server_name": "${SERVER_NAME}"
          }
        },
        "brand": "Cyber",
        "default_federate": false,
        "default_theme": "light",
        "default_country_code": "DE",
        "disable_guests": false,
        "disable_3pid_login": true,
        "show_labs_settings": false,
        "element_call": {
          "url": "${ELEMENT_CALL_URL}",
          "use_exclusively": true,
          "participant_limit": 8,
          "brand": "Cyber"
        },
        "roomDirectory": { "servers": [] }
      }
