services:
  tuwunel:
    image: ghcr.io/matrix-construct/tuwunel:v1.8.2
    restart: always
    environment:
      - TUWUNEL_SERVER_NAME=${TUWUNEL_SERVER_NAME}
      - TUWUNEL_ALLOW_REGISTRATION=${TUWUNEL_ALLOW_REGISTRATION}
      - TUWUNEL_REGISTRATION_TOKEN=${TUWUNEL_REGISTRATION_TOKEN}
      - TUWUNEL_ADDRESS=${TUWUNEL_ADDRESS}
      - TUWUNEL_PORT=${TUWUNEL_PORT}
      - TUWUNEL_IDENTITY_PROVIDER__0__BRAND=${TUWUNEL_OIDC_PROVIDER}
      - TUWUNEL_IDENTITY_PROVIDER__0__CLIENT_ID=${TUWUNEL_OIDC_CLIENT_ID}
      - TUWUNEL_IDENTITY_PROVIDER__0__CLIENT_SECRET=${TUWUNEL_OIDC_CLIENT_SECRET}
      - TUWUNEL_IDENTITY_PROVIDER__0__ISSUER_URL=${TUWUNEL_OIDC_ISSUER_URL}
      - TUWUNEL_IDENTITY_PROVIDER__0__CALLBACK_URL=${TUWUNEL_OIDC_CALLBACK_URL}

    volumes:
      - tuwunel-data:/var/lib/tuwunel/
    expose:
      - 6167
    ports:
      - ${TUWUNEL_PORTS}

volumes:
  tuwunel-data:
