services:
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:v1.13.2
    restart: unless-stopped
    expose:
      - 3000
    volumes:
      - ${HOMEPAGE_CONFIG_DIR}:/app/config
      - ${HOMEPAGE_ICONS_DIR}:/app/public/icons
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=${HOMEPAGE_ALLOWED_HOSTS}
